### ISSUE TITLE
Does this work with the current version of etherpad? 

### ISSUE THREAD

**Issue by woeterman94** [JohnMcLear/ep_inline_toolbar#3]
Is this plugin still being maintained? Does it work with the current version of etherpad?

```
[2020-10-21 18:02:11.056] [ERROR] console - (node:8584) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at Object.createInlineToolbar (C:\Users\dum\Documents\Code\etherpad\node_modules\ep_inline_toolbar\index.js:27:21)
    at executeBound (C:\Users\dum\Documents\Code\etherpad\node_modules\ep_inline_toolbar\node_modules\underscore\underscore.js:897:67)
    at C:\Users\dum\Documents\Code\etherpad\node_modules\ep_inline_toolbar\node_modules\underscore\underscore.js:929:14
    at C:\Users\dum\Documents\Code\etherpad\node_modules\ep_inline_toolbar\node_modules\underscore\underscore.js:73:29
    at Object.exports.clientVars [as hook_fn] (C:\Users\dum\Documents\Code\etherpad\node_modules\ep_inline_toolbar\index.js:16:3)
    at normalizedhook (C:\Users\dum\Documents\Code\etherpad\node_modules\ep_etherpad-lite\static\js\pluginfw\hooks.js:38:27)
    at hookCallWrapper (C:\Users\dum\Documents\Code\etherpad\node_modules\ep_etherpad-lite\static\js\pluginfw\hooks.js:44:14)
    at C:\Users\dum\Documents\Code\etherpad\node_modules\ep_etherpad-lite\static\js\pluginfw\hooks.js:109:18
    at Array.map (<anonymous>)
    at aCallAll (C:\Users\dum\Documents\Code\etherpad\node_modules\ep_etherpad-lite\static\js\pluginfw\hooks.js:108:51)
```

**Comment by JohnMcLear** [comment]
I just fixed the bugs, 0.1.0 should work.   https://github.com/JohnMcLear/ep_inline_toolbar/commits?author=JohnMcLear
